---

services:
  validator:
    build: 
      context: .
    environment:
      - PYTHONPATH=.
    ports:
      - ${BT_AXON_VALIDATOR_PORT}:${BT_AXON_VALIDATOR_PORT}
    volumes:
      - ${HOME}/.bittensor:/root/.bittensor
    command: "neurons/validator.py --subtensor.network ${BT_NETWORK} --netuid ${BT_NETUID} --wallet.name ${BT_VALIDATOR_COLDKEY} --wallet.hotkey ${BT_VALIDATOR_HOTKEY} --axon.port ${BT_AXON_VALIDATOR_PORT} --axon.ip ${BT_AXON_IP} --axon.external_port ${BT_AXON_VALIDATOR_PORT} --axon.external_ip ${BT_AXON_IP}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
