_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 71
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
hotkey:
    value: 5FYoRCx8ViMm6ZNZ9itjuzE8pdzFNKCRVR6F2VHmkTFekZVG
run_id:
    value: 2024-10-14-14-45-44
type:
    value: validator
uid:
    value: 7
