services:
  miner1:
    image: sylliba
    environment:
      - PYTHONPATH=.
    ports:
      - ${BT_AXON_MINER1_PORT}:${BT_AXON_MINER1_PORT}
    volumes:
      - ${HOME}/.bittensor:/root/.bittensor
    command: "neurons/miner.py --subtensor.network ${BT_NETWORK} --netuid ${BT_NETUID} --wallet.name ${BT_MINER_COLDKEY} --wallet.hotkey ${BT_MINER1_HOTKEY} --axon.port ${BT_AXON_MINER1_PORT} --axon.ip ${BT_AXON_IP} --axon.external_port ${BT_AXON_MINER1_PORT} --axon.external_ip ${BT_AXON_IP}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]   

  miner2:
    image: sylliba
    environment:
      - PYTHONPATH=.
    ports:
      - ${BT_AXON_MINER2_PORT}:${BT_AXON_MINER2_PORT}
    volumes:
      - ${HOME}/.bittensor:/root/.bittensor
    command: "neurons/miner.py --subtensor.network ${BT_NETWORK} --netuid ${BT_NETUID} --wallet.name ${BT_MINER_COLDKEY} --wallet.hotkey ${BT_MINER2_HOTKEY} --axon.port ${BT_AXON_MINER2_PORT} --axon.ip ${BT_AXON_IP} --axon.external_port ${BT_AXON_MINER2_PORT} --axon.external_ip ${BT_AXON_IP}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]         

  miner3:
    image: sylliba
    environment:
      - PYTHONPATH=.
    ports:
      - ${BT_AXON_MINER3_PORT}:${BT_AXON_MINER3_PORT}
    volumes:
      - ${HOME}/.bittensor:/root/.bittensor
    command: "neurons/miner.py --subtensor.network ${BT_NETWORK} --netuid ${BT_NETUID} --wallet.name ${BT_MINER_COLDKEY} --wallet.hotkey ${BT_MINER3_HOTKEY} --axon.port ${BT_AXON_MINER3_PORT} --axon.ip ${BT_AXON_IP} --axon.external_port ${BT_AXON_MINER3_PORT} --axon.external_ip ${BT_AXON_IP}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]         
