name: Deploy Validator

on: 
  workflow_call:
    inputs:
      gpu_index_vali:
        required: false
        type: string
        default: "all"
      gpu_index_miner:
        required: false
        type: string
        default: "all"      
      image_tag:
        required: false
        type: string
        default: "today"
      microservice:
          required: false
          type: string
          default: "service"
      microservice_path:
        required: false
        type: string
        default: ./
        description: path for service
      microservice_env:
        required: false
        type: string
        default: dev
        description: the environment
      context_dir:
        required: false
        type: string
        default: .
        description: docker context
      image_registry:
        required: false
        type: string
        default: dev
        description: The registery to upload the docker image to
      deployment_servers:
        required: false
        type: string
        description: the servers to deploy to
      branch:
        required: false
        type: string
        default: main
        description: the default branch
      BT_NETWORK:
        required: false
        type: string
        default: "test"
      BT_NETUID:
        required: false
        default: "197"
        type: string
      BT_AXON_MAX_WORKERS:
        required: false
        default: "5"
        type: string
      BT_WALLET_PATH:
        required: false
        type: string
      SUBNET_API_PORT:
        required: false
        type: string
      BT_MINER_COLDKEY:
        required: false
        type: string
      BT_MINER_HOTKEY:
        required: false
        type: string
      BT_AXON_MINER_IP:
        required: false
        type: string
      BT_AXON_MINER_PORT:
        required: false
        type: string
      BT_AXON_MINER_EXTERNAL_IP:
        required: false
        type: string
      BT_AXON_MINER_EXTERNAL_PORT:
        required: false
        type: string
      BT_VALIDATOR_COLDKEY:
        required: false
        type: string
      BT_VALIDATOR_HOTKEY:
        required: false
        type: string
      BT_AXON_VALIDATOR_IP:
        required: false
        type: string
      BT_AXON_VALIDATOR_PORT:
        required: false
        type: string
      BT_AXON_VALIDATOR_EXTERNAL_PORT:
        required: false
        type: string
      BT_AXON_VALIDATOR_EXTERNAL_IP:
        required: false
        type: string
      PYTHONPATH:
        required: false
        type: string

jobs:         
  Deploy-Microservice:
    runs-on: [self-hosted, "${{ matrix.deployment_server }}" ]
    strategy:
      matrix:
        deployment_server: ${{ fromJson(inputs.deployment_servers) }}

    steps:
      - name: Convert Docker Registry Repo to lowercase
        env:
          image_registry: ${{ inputs.image_registry }}      
        run: |
          REPO=$(echo "$image_registry" | tr '[:upper:]' '[:lower:]')
          echo "REPO=$REPO" >> $GITHUB_ENV

      - name: Docker stop old container
        run: |
          docker container rm -f ${{inputs.microservice}}-validator-${{inputs.microservice_env}} || $true

      - name: Docker start new container
        run: >-
          docker run
          --name ${{inputs.microservice}}-validator-${{inputs.microservice_env}}
          --restart always
          -p ${{inputs.BT_AXON_VALIDATOR_EXTERNAL_PORT}}:${{inputs.BT_AXON_VALIDATOR_EXTERNAL_PORT}}
          -v /home/ubuntu/.bittensor/wallets:/root/.bittensor/wallets
          -e APP_VERSION=$GITHUB_REF_NAME
          -e environment=${{inputs.microservice_env}}
          -e BT_NETWORK=${{inputs.BT_NETWORK}}
          -e BT_NETUID=${{inputs.BT_NETUID}}
          -e BT_AXON_MAX_WORKERS=${{inputs.BT_AXON_MAX_WORKERS}}
          -e BT_WALLET_PATH=${{inputs.BT_WALLET_PATH}}
          -e SUBNET_API_PORT=${{inputs.SUBNET_API_PORT}}
          -e BT_AXON_MINER_PORT=${{inputs.BT_AXON_MINER_PORT}}
          -e BT_AXON_MINER_IP=${{inputs.BT_AXON_MINER_IP}}
          -e BT_AXON_MINER_EXTERNAL_PORT=${{inputs.BT_AXON_MINER_EXTERNAL_PORT}}
          -e BT_AXON_MINER_EXTERNAL_IP=${{inputs.BT_AXON_MINER_EXTERNAL_IP}}
          -e BT_MINER_COLDKEY=${{inputs.BT_MINER_COLDKEY}}
          -e BT_MINER_HOTKEY=${{inputs.BT_MINER_HOTKEY}}
          -e BT_AXON_VALIDATOR_PORT=${{inputs.BT_AXON_VALIDATOR_PORT}}
          -e BT_AXON_VALIDATOR_IP=${{inputs.BT_AXON_VALIDATOR_IP}}
          -e BT_AXON_VALIDATOR_EXTERNAL_PORT=${{inputs.BT_AXON_VALIDATOR_EXTERNAL_PORT}}
          -e BT_AXON_VALIDATOR_EXTERNAL_IP=${{inputs.BT_AXON_VALIDATOR_EXTERNAL_IP}}          
          -e BT_VALIDATOR_COLDKEY=${{inputs.BT_VALIDATOR_COLDKEY}}
          -e BT_VALIDATOR_HOTKEY=${{inputs.BT_VALIDATOR_HOTKEY}}          
          -e PYTHONPATH=${{inputs.PYTHONPATH}}
          --gpus ${{inputs.gpu_index_vali}}
          --add-host host.docker.internal:host-gateway
          -d ${{env.REPO}}/${{ inputs.microservice }}-${{ inputs.microservice_env }}:${{ inputs.image_tag }} neurons/validator.py --logging.debug
