name: Deploy Miner

on: 
  workflow_call:
    inputs:
      gpu_index_vali:
        required: false
        type: string
        default: "all"
      gpu_index_miner:
        required: false
        type: string
        default: "all"
      image_tag:
        required: false
        type: string
        default: "today"
      microservice:
          required: false
          type: string
          default: "service"
      microservice_path:
        required: false
        type: string
        default: ./
        description: path for service
      microservice_env:
        required: false
        type: string
        default: dev
        description: the environment
      context_dir:
        required: false
        type: string
        default: .
        description: docker context
      image_registry:
        required: false
        type: string
        default: dev
        description: The registery to upload the docker image to
      deployment_servers:
        required: false
        type: string
        description: the servers to deploy to
      branch:
        required: false
        type: string
        default: main
        description: the default branch
      BT_NETWORK:
        required: false
        type: string
        default: "test"
      BT_NETUID:
        required: false
        default: "197"
        type: string
      BT_AXON_MAX_WORKERS:
        required: false
        default: "5"
        type: string
      BT_WALLET_PATH:
        required: false
        type: string
      SUBNET_API_PORT:
        required: false
        type: string
      BT_MINER_COLDKEY:
        required: false
        type: string
      BT_MINER_HOTKEY:
        required: false
        type: string
      BT_AXON_MINER_IP:
        required: false
        type: string
      BT_AXON_MINER_PORT:
        required: false
        type: string
      BT_AXON_MINER_EXTERNAL_IP:
        required: false
        type: string
      BT_AXON_MINER_EXTERNAL_PORT:
        required: false
        type: string
      BT_VALIDATOR_COLDKEY:
        required: false
        type: string
      BT_VALIDATOR_HOTKEY:
        required: false
        type: string
      BT_AXON_VALIDATOR_IP:
        required: false
        type: string
      BT_AXON_VALIDATOR_PORT:
        required: false
        type: string
      BT_AXON_VALIDATOR_EXTERNAL_PORT:
        required: false
        type: string
      BT_AXON_VALIDATOR_EXTERNAL_IP:
        required: false
        type: string
      PYTHONPATH:
        required: false
        type: string

jobs:         
  Deploy-Microservice:
    runs-on: [self-hosted, "${{ matrix.deployment_server }}" ]
    strategy:
      matrix:
        deployment_server: ${{ fromJson(inputs.deployment_servers) }}

    steps:
      # - uses: actions/checkout@v4
      #   with:
      #     ref: ${{ inputs.branch }}
          
      # - name: Login to GHCR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}          

      - name: Convert Docker Registry Repo to lowercase
        env:
          image_registry: ${{ inputs.image_registry }}      
        run: |
          REPO=$(echo "$image_registry" | tr '[:upper:]' '[:lower:]')
          echo "REPO=$REPO" >> $GITHUB_ENV

      - name: Docker stop old container
        run: |
          docker container rm -f ${{inputs.microservice}}-miner-${{inputs.microservice_env}} || $true

      - name: Docker start new container
        run: >-
          docker run
          --name ${{inputs.microservice}}-miner-${{inputs.microservice_env}}
          --restart always
          -p ${{inputs.BT_AXON_MINER_PORT}}:${{inputs.BT_AXON_MINER_PORT}}
          -v /home/ubuntu/.bittensor/wallets:/root/.bittensor/wallets
          -e APP_VERSION=$GITHUB_REF_NAME
          -e environment=${{inputs.microservice_env}}
          -e SUBNET_API_PORT=${{inputs.SUBNET_API_PORT}}
          -e PYTHONPATH=${{inputs.PYTHONPATH}}
          --gpus "device=${{inputs.gpu_index_miner}}"
          --add-host host.docker.internal:host-gateway
          -d ${{env.REPO}}/${{ inputs.microservice }}-${{ inputs.microservice_env }}:${{ inputs.image_tag }} neurons/miner.py
          --netuid ${{inputs.BT_NETUID}}
          --subtensor.network ${{inputs.BT_NETWORK}}
          --wallet.path ${{inputs.BT_WALLET_PATH}}
          --wallet.name ${{inputs.BT_MINER_COLDKEY}}
          --wallet.hotkey ${{inputs.BT_MINER_HOTKEY}}
          --axon.ip ${{inputs.BT_AXON_MINER_IP}}
          --axon.port ${{inputs.BT_AXON_MINER_PORT}}
          --axon.external_ip ${{inputs.BT_AXON_MINER_EXTERNAL_IP}}
          --axon.external_port ${{inputs.BT_AXON_MINER_EXTERNAL_PORT}}
          --axon.max_workers ${{inputs.BT_AXON_MAX_WORKERS}}
